[build]
  command = "npm run build"
  publish = "frontend/dist"

[dev]
  framework = "#custom"
  command = "npm run dev:all"
  targetPort = 3000
  port = 8888

[functions]
  directory = "netlify/functions"
